# Generated by Django 5.1.7 on 2025-06-03 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewme', '0006_answer_anonymous_answerlike_notified_media_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlike',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='questionupvote',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='reviewlike',
            name='notified',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('review', 'review'), ('question', 'question'), ('answer', 'answer')], default='review', max_length=50)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reviewme.answer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reviewme.question')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reviewme.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
